import type { Metadata } from 'next';
import { Raleway, Open_Sans } from 'next/font/google';
import Header from '@/components/Header/Header';
import './styles/main.css';

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
});

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${openSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
